{
	name: "🐛 Bug Report",
	description: "File an issue concerning an existing template or partial.",
	assignees: ["ciosciaa"],
	labels: "Bug",
	
	body: [
		{
			type: "markdown",
			attributes: {
				value: "
					# Usage\n
					Submit a bug report here.\n
					\n
					For *support* on how to use templates and partials, create a new discussion instead. If desiring a new template or partial, file a [request for such](https://github.com/united-paradigms/test/issues/new?template=1-file-request.yaml) instead. If desiring content updates to templates and partials, file a [request for such](https://github.com/united-paradigms/test/issues/new?template=2-content-update.yaml) instead.\n
					\n
					# Form
				"
			}
		},
		{
			type: "textarea",
			id: "files",
			attributes: {
				label: "Files",
				description: "Specify the template(s) and/or partial(s) causing problems.",
				placeholder: "templates/browser/library/development.json"
			},
			validations: {required: true}
		},
		{
			type: "textarea",
			id: "description",
			attributes: {
				label: "Description",
				description: "Describe the issue with the noted files.",
				placeholder: "A compiler option has been deprecated."
			},
			validations: {required: true}
		}
	]
}