{
	name: "📄 File Request",
	description: "Request a new template or partial.",
	assignees: ["ciosciaa"],
	labels: "Feature Request",
	
	body: [
		{
			type: "markdown",
			attributes: {
				value: "
					# Usage\n
					Request a new template or partial here.\n
					\n
					For *support* on template or partial organization, create a new discussion instead. To bring attention to a bug with an existing template or partial, file a [bug report](https://github.com/united-paradigms/test/issues/new?template=0-bug-report.yaml) instead. If desiring content updates to templates and partials, file a [request for such](https://github.com/united-paradigms/test/issues/new?template=2-content-update.yaml) instead.\n
					\n
					# Form
				"
			}
		},
		{
			type: "textarea",
			id: "files",
			attributes: {
				label: "Files",
				description: "Specify the template(s) and/or partial(s) that should be created.",
				placeholder: "templates/deno"
			},
			validations: {required: true}
		},
		{
			type: "textarea",
			id: "justification",
			attributes: {
				label: "Justification",
				description: "Justify why the specified files should be added.",
				placeholder: "Deno is an increasingly used ecosystem that has different needs than Node."
			},
			validations: {required: true}
		}
	]
}