{
	blank_issues_enabled: false,
	contact_links: [
		{
			name: "Community Support",
			about: "Join our community Discord server for fast help.",
			url: "https://discord.unitedparadigms.com/"
		}
	]
}